description = "Utility Library REST support on top of AWS"
long-description = "\n[![Build Status](https://img.shields.io/jenkins/s/https/jenkins.vacs.fr/Ada-Util.svg)](https://jenkins.vacs.fr/job/Ada-Util/)\n[![Test Status](https://img.shields.io/jenkins/t/https/jenkins.vacs.fr/Ada-Util.svg)](https://jenkins.vacs.fr/job/Ada-Util/)\n[![codecov](https://codecov.io/gh/stcarrez/ada-util/branch/master/graph/badge.svg)](https://codecov.io/gh/stcarrez/ada-util)\n\n\nThis small library provides an HTTP backend on top of AWS.\nIt is can be used by the `Util.Http` package.\n\nAn alternate HTTP backend is provided by CURL with utilada_curl.\n\n"
name = "utilada_aws"
version = "2.5.0"
authors = ["Stephane.Carrez@gmail.com"]
licenses = "Apache-2.0"
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = [".alire/aws/utilada_aws.gpr"]
tags = ["web", "http"]
website = "https://gitlab.com/stcarrez/ada-util"

[[depends-on]]
utilada = "^2.5.0"
aws = "~21.0"

[gpr-externals]
BUILD = ["distrib", "debug", "optimize", "profile", "coverage"]
UTIL_LIBRARY_TYPE = ["relocatable", "static", "static-pic"]
UTIL_AWS_IMPL = ["1", "2", "3"]

[gpr-set-externals]
UTIL_AWS_IMPL = "2"

[configuration]
disabled = true
