description = "Utility Library REST support on top of CURL"
long-description = "\n[![Build Status](https://img.shields.io/jenkins/s/https/jenkins.vacs.fr/Ada-Util.svg)](https://jenkins.vacs.fr/job/Ada-Util/)\n[![Test Status](https://img.shields.io/jenkins/t/https/jenkins.vacs.fr/Ada-Util.svg)](https://jenkins.vacs.fr/job/Ada-Util/)\n[![codecov](https://codecov.io/gh/stcarrez/ada-util/branch/master/graph/badge.svg)](https://codecov.io/gh/stcarrez/ada-util)\n\n\nThis small library provides an HTTP backend on top of CURL.\nIt is can be used by the `Util.Http` package.\n\nAn alternate HTTP backend is provided by AWS with utilada_aws.\n\n"
name = "utilada_curl"
version = "2.5.0"
authors = ["Stephane.Carrez@gmail.com"]
licenses = "Apache-2.0"
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["utilada_curl.gpr"]
tags = ["web", "http", "rest"]
website = "https://gitlab.com/stcarrez/ada-util"

[[depends-on]]
utilada = "^2.5.0"
curl = "*"

[gpr-externals]
BUILD = ["distrib", "debug", "optimize", "profile", "coverage"]
UTIL_LIBRARY_TYPE = ["relocatable", "static", "static-pic"]

[configuration]
disabled = true
