--  Generated by utildgen.c from system includes
private package Util.Http.Clients.Curl.Constants is

   CURLOPT_URL            : constant Curl_Option := 10002;
   CURLOPT_HTTPGET        : constant Curl_Option := 80;
   CURLOPT_POST           : constant Curl_Option := 47;
   CURLOPT_CUSTOMREQUEST  : constant Curl_Option := 10036;
   CURLOPT_READFUNCTION   : constant Curl_Option := 20012;
   CURLOPT_WRITEUNCTION   : constant Curl_Option := 20011;
   CURLOPT_HTTPHEADER     : constant Curl_Option := 10023;
   CURLOPT_INTERFACE      : constant Curl_Option := 10062;
   CURLOPT_USERPWD        : constant Curl_Option := 10005;
   CURLOPT_HTTPAUTH       : constant Curl_Option := 107;
   CURLOPT_MAXFILESIZE    : constant Curl_Option := 114;
   CURLOPT_WRITEDATA      : constant Curl_Option := 10001;
   CURLOPT_HEADER         : constant Curl_Option := 42;
   CURLOPT_POSTFIELDS     : constant Curl_Option := 10015;
   CURLOPT_POSTFIELDSIZE  : constant Curl_Option := 60;
   CURLOPT_CONNECTTIMEOUT : constant Curl_Option := 78;
   CURLOPT_TIMEOUT        : constant Curl_Option := 13;
   CURLOPT_NOBODY         : constant Curl_Option := 44;

   CURLINFO_RESPONSE_CODE : constant CURL_Info := 2097154;

end Util.Http.Clients.Curl.Constants;
