#!/bin/sh
# postinst script for libada-util
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

has_aws="no"
has_curl="no"
if [ -f /usr/share/ada/adainclude/util_http_curl.gpr ]; then
  has_curl="yes"
fi
if [ -f /usr/share/ada/adainclude/util_http_aws.gpr ]; then
  has_aws="yes"
fi
(echo 'with "util";';
 test "$has_curl" = "yes" || echo 'with "util_http_curl";'
 test "$has_aws" = "yes" || echo 'with "util_http_aws";'
 echo 'abstract project Util_Http is'
 echo '   type Yes_No is ("yes", "no");'
 echo '   Has_Curl    : Yes_No := "'$has_curl'";'
 echo '   Has_AWS     : Yes_No := "'$has_aws'";'
 echo "end Util_Http;"
) > /usr/share/ada/adainclude/util_http.gpr

case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
